//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppcCityBusStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int IDTicket { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int Age { get; set; }
        public string PassportSeriesAndNumber { get; set; }
        public int Schedule { get; set; }
        public int PlaceNumber { get; set; }
        public Nullable<bool> Pets { get; set; }
        public bool BoughtOut { get; set; }
    
        public virtual Schedules Schedules { get; set; }
    }
}
